### ISSUE TITLE
수치 미분 방식으로 기울기를 계산하여 학습을 진행할 때의 학습 속도 문제

### ISSUE THREAD

**Issue by hcm1206** [hcm1206/DeepLearningStudy#1]
배치를 획득하고 기울기를 계산하여 매개변수를 갱신하고 학습 경과를 리스트로 저장하는 것까지가 학습 한 번의 과정인데
10000 번의 학습을 진행해야 하는데 대략 5분에 10번 정도의 비율로 학습이 진행됩니다.
별다른 오류가 출력되지 않고 prac-10(4.5.2) 코드와 prac-11(4.5.3) 코드 둘 다 실행 속도가 느린 것을 보면 코드 문제는 아닌 것 같습니다. (두 코드를 작성할 때 복사하지 않고 모두 직접 타이핑하였기 때문에 코드 오류일 확률은 낮음)
클래스 코드도 확인해보았을 때 별 문제가 없는 것으로 보이고 클래스에서 사용한 함수들도 이전 실습을 통해 검증된 코드들이라 문제는 없습니다.

코드 실행 과정을 분석해본 결과 W1(첫번째 층 가중치) 매개변수의 기울기 계산에서 대부분의 시간이 소요되는것으로 확인되는데
W1 매개변수가 784×50 크기의 행렬로 상당한 크기를 가지고 있고
책에 의하면 수치 미분 방식으로 기울기를 계산할 시 계산이 오래 걸린다고 하기는 합니다.

그런데 학습 과정이 이 정도로 오래 걸리는 것이 정상적인지는 모르겠습니다.
랩탑 PC로 프로세스를 돌리느라 PC의 사양 문제인지 원래 수치 미분 방식이 이렇게 오래 걸리는 것인지 현재 알 수 없습니다.
다음 장에서 수치 미분 방식보다 더 고속으로 계산하는 오차역전파법을 사용한다는데
그 때 계산 속도를 비교해봐야겠습니다.

**Comment by mnyu123** [comment]
tensorflow - gpu 라이브러리 사용 & 구글 코랩 사용(구글의 cpu를 사용하면 개인 pc환경보다 빠르다.)

**Comment by mnyu123** [comment]
![코랩사용추천](https://user-images.githubusercontent.com/50972003/178099407-2267a5e2-a9b1-4d15-b9a6-5aaa1b2e1fda.PNG)
> 사진으로 보듯이 코랩의 gpu사용으로 6만개의 데이터 정도는 빠르게 학습이 가능하다

**Comment by hcm1206** [comment]
> tensorflow - gpu 라이브러리 사용 & 구글 코랩 사용(구글의 cpu를 사용하면 개인 pc환경보다 빠르다.)

추후 확인해보겠습니다.

**Comment by hcm1206** [comment]
오차역전파법을 이용하여 계산해보니 결과가 빠르게 도출되는 것이 확인되었습니다.
추가로 수치 미분 방식과 오차역전파법을 같이 사용하여 기울기 값을 교차검증하는 '기울기 확인' 과정을 거쳤는데
계산 결과에 오차가 거의 없는 것으로 보니 구현이 잘못된 것은 아닌 것 같고
수치 미분 방식이 그냥 계산 속도가 많이 느린 것으로 보입니다.
